name: Cypress Tests

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:
    inputs:
      browserName:
        description: "Browser to use for Cypress tests"
        required: false
        default: "chrome"
      specName:
        description: "Dynamically choose which test file to run"
        required: false
        default: "" # Default: Run all tests

jobs:
  cypress-run:
    runs-on: windows-latest

    # strategy:
    #   fail-fast: false
    #   matrix:
    #     containers: [1, 2]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Start Application
        run: npm start &

      - name: Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          record: true
          headed: true
          # parallel: true
          browser: ${{ github.event.inputs.browserName || 'chrome' }}
          spec: ${{ github.event.inputs.specName || 'cypress/e2e/**/*' }} # Pass the test file path dynamically

        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
